package raven.game.messaging;

public enum RavenMessage {
	MSG_BLANK,
	MSG_PATH_READY,
	MSG_NO_PATH_AVAILABLE,
	MSG_TAKE_THAT_MF,
	MSG_YOU_GOT_ME_YOU_SOB,
	MSG_GOAL_QUEUE_EMPTY,
	MSG_OPEN_SESAME,
	MSG_GUNSHOT_SOUND,
	MSG_USER_HAS_REMOVED_BOT;
}
